name: mimij
version: 1.0.0
summary: A simple audio player
description: A simple audio player that supports AB area repeat

confinement: strict
base: core18
grade: stable

slots:
  dbus-mimij: # adjust accordingly to your app name
    interface: dbus
    bus: session
    name: com.technicalfeeder.mimij # adjust accordingly to your app name and
    
apps:
  mimij:
    command: mimij
    extensions: [flutter-master] # Where "master" defines which Flutter channel to use for the build
    plugs:
    - network
    slots:
      - dbus-mimij
parts:
  mimij:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart # The main entry-point file of the application
